//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 08:50:01 AM PDT 
//


package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openpnp.model.eagle package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openpnp.model.eagle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Busses }
     * 
     */
    public Busses createBusses() {
        return new Busses();
    }

    /**
     * Create an instance of {@link Bus }
     * 
     */
    public Bus createBus() {
        return new Bus();
    }

    /**
     * Create an instance of {@link Junction }
     * 
     */
    public Junction createJunction() {
        return new Junction();
    }

    /**
     * Create an instance of {@link Symbol }
     * 
     */
    public Symbol createSymbol() {
        return new Symbol();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Polygon }
     * 
     */
    public Polygon createPolygon() {
        return new Polygon();
    }

    /**
     * Create an instance of {@link Wire }
     * 
     */
    public Wire createWire() {
        return new Wire();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link Pin }
     * 
     */
    public Pin createPin() {
        return new Pin();
    }

    /**
     * Create an instance of {@link Circle }
     * 
     */
    public Circle createCircle() {
        return new Circle();
    }

    /**
     * Create an instance of {@link Rectangle }
     * 
     */
    public Rectangle createRectangle() {
        return new Rectangle();
    }

    /**
     * Create an instance of {@link Frame }
     * 
     */
    public Frame createFrame() {
        return new Frame();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Vertex }
     * 
     */
    public Vertex createVertex() {
        return new Vertex();
    }

    /**
     * Create an instance of {@link Variantdefs }
     * 
     */
    public Variantdefs createVariantdefs() {
        return new Variantdefs();
    }

    /**
     * Create an instance of {@link Variantdef }
     * 
     */
    public Variantdef createVariantdef() {
        return new Variantdef();
    }

    /**
     * Create an instance of {@link Via }
     * 
     */
    public Via createVia() {
        return new Via();
    }

    /**
     * Create an instance of {@link Setting }
     * 
     */
    public Setting createSetting() {
        return new Setting();
    }

    /**
     * Create an instance of {@link Pad }
     * 
     */
    public Pad createPad() {
        return new Pad();
    }

    /**
     * Create an instance of {@link Approved }
     * 
     */
    public Approved createApproved() {
        return new Approved();
    }

    /**
     * Create an instance of {@link Connects }
     * 
     */
    public Connects createConnects() {
        return new Connects();
    }

    /**
     * Create an instance of {@link Connect }
     * 
     */
    public Connect createConnect() {
        return new Connect();
    }

    /**
     * Create an instance of {@link Plain }
     * 
     */
    public Plain createPlain() {
        return new Plain();
    }

    /**
     * Create an instance of {@link Hole }
     * 
     */
    public Hole createHole() {
        return new Hole();
    }

    /**
     * Create an instance of {@link Pinref }
     * 
     */
    public Pinref createPinref() {
        return new Pinref();
    }

    /**
     * Create an instance of {@link Portref }
     * 
     */
    public Portref createPortref() {
        return new Portref();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Drawing }
     * 
     */
    public Drawing createDrawing() {
        return new Drawing();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Grid }
     * 
     */
    public Grid createGrid() {
        return new Grid();
    }

    /**
     * Create an instance of {@link Layers }
     * 
     */
    public Layers createLayers() {
        return new Layers();
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link Schematic }
     * 
     */
    public Schematic createSchematic() {
        return new Schematic();
    }

    /**
     * Create an instance of {@link Board }
     * 
     */
    public Board createBoard() {
        return new Board();
    }

    /**
     * Create an instance of {@link Layer }
     * 
     */
    public Layer createLayer() {
        return new Layer();
    }

    /**
     * Create an instance of {@link Variant }
     * 
     */
    public Variant createVariant() {
        return new Variant();
    }

    /**
     * Create an instance of {@link Moduleinst }
     * 
     */
    public Moduleinst createModuleinst() {
        return new Moduleinst();
    }

    /**
     * Create an instance of {@link Net }
     * 
     */
    public Net createNet() {
        return new Net();
    }

    /**
     * Create an instance of {@link Signal }
     * 
     */
    public Signal createSignal() {
        return new Signal();
    }

    /**
     * Create an instance of {@link Contactref }
     * 
     */
    public Contactref createContactref() {
        return new Contactref();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Smd }
     * 
     */
    public Smd createSmd() {
        return new Smd();
    }

    /**
     * Create an instance of {@link Devices }
     * 
     */
    public Devices createDevices() {
        return new Devices();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Pass }
     * 
     */
    public Pass createPass() {
        return new Pass();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Ports }
     * 
     */
    public Ports createPorts() {
        return new Ports();
    }

    /**
     * Create an instance of {@link Parts }
     * 
     */
    public Parts createParts() {
        return new Parts();
    }

    /**
     * Create an instance of {@link Sheets }
     * 
     */
    public Sheets createSheets() {
        return new Sheets();
    }

    /**
     * Create an instance of {@link Libraries }
     * 
     */
    public Libraries createLibraries() {
        return new Libraries();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Classes }
     * 
     */
    public Classes createClasses() {
        return new Classes();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Packages }
     * 
     */
    public Packages createPackages() {
        return new Packages();
    }

    /**
     * Create an instance of {@link Technologies }
     * 
     */
    public Technologies createTechnologies() {
        return new Technologies();
    }

    /**
     * Create an instance of {@link Technology }
     * 
     */
    public Technology createTechnology() {
        return new Technology();
    }

    /**
     * Create an instance of {@link Signals }
     * 
     */
    public Signals createSignals() {
        return new Signals();
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link Eagle }
     * 
     */
    public Eagle createEagle() {
        return new Eagle();
    }

    /**
     * Create an instance of {@link Compatibility }
     * 
     */
    public Compatibility createCompatibility() {
        return new Compatibility();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Devicesets }
     * 
     */
    public Devicesets createDevicesets() {
        return new Devicesets();
    }

    /**
     * Create an instance of {@link Deviceset }
     * 
     */
    public Deviceset createDeviceset() {
        return new Deviceset();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Designrules }
     * 
     */
    public Designrules createDesignrules() {
        return new Designrules();
    }

    /**
     * Create an instance of {@link Instances }
     * 
     */
    public Instances createInstances() {
        return new Instances();
    }

    /**
     * Create an instance of {@link Nets }
     * 
     */
    public Nets createNets() {
        return new Nets();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Gates }
     * 
     */
    public Gates createGates() {
        return new Gates();
    }

    /**
     * Create an instance of {@link Symbols }
     * 
     */
    public Symbols createSymbols() {
        return new Symbols();
    }

    /**
     * Create an instance of {@link Gate }
     * 
     */
    public Gate createGate() {
        return new Gate();
    }

    /**
     * Create an instance of {@link Sheet }
     * 
     */
    public Sheet createSheet() {
        return new Sheet();
    }

    /**
     * Create an instance of {@link Moduleinsts }
     * 
     */
    public Moduleinsts createModuleinsts() {
        return new Moduleinsts();
    }

    /**
     * Create an instance of {@link Clearance }
     * 
     */
    public Clearance createClearance() {
        return new Clearance();
    }

    /**
     * Create an instance of {@link Autorouter }
     * 
     */
    public Autorouter createAutorouter() {
        return new Autorouter();
    }

    /**
     * Create an instance of {@link Elements }
     * 
     */
    public Elements createElements() {
        return new Elements();
    }

}
