//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 08:50:01 AM PDT 
//


package org.openpnp.model.eagle.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactrefOrPolygonOrWireOrVia"
})
@XmlRootElement(name = "signal")
public class Signal {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "class")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String clazz;
    @XmlAttribute(name = "airwireshidden")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String airwireshidden;
    @XmlElements({
        @XmlElement(name = "contactref", type = Contactref.class),
        @XmlElement(name = "polygon", type = Polygon.class),
        @XmlElement(name = "wire", type = Wire.class),
        @XmlElement(name = "via", type = Via.class)
    })
    protected List<Object> contactrefOrPolygonOrWireOrVia;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        if (clazz == null) {
            return "0";
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the airwireshidden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwireshidden() {
        if (airwireshidden == null) {
            return "no";
        } else {
            return airwireshidden;
        }
    }

    /**
     * Sets the value of the airwireshidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwireshidden(String value) {
        this.airwireshidden = value;
    }

    /**
     * Gets the value of the contactrefOrPolygonOrWireOrVia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactrefOrPolygonOrWireOrVia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactrefOrPolygonOrWireOrVia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contactref }
     * {@link Polygon }
     * {@link Wire }
     * {@link Via }
     * 
     * 
     */
    public List<Object> getContactrefOrPolygonOrWireOrVia() {
        if (contactrefOrPolygonOrWireOrVia == null) {
            contactrefOrPolygonOrWireOrVia = new ArrayList<>();
        }
        return this.contactrefOrPolygonOrWireOrVia;
    }

}
