//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//


package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"value"})
@XmlRootElement(name = "text")
public class Text {

    @XmlAttribute(name = "x", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String x;
    @XmlAttribute(name = "y", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String y;
    @XmlAttribute(name = "size", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String size;
    @XmlAttribute(name = "layer", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String layer;
    @XmlAttribute(name = "font")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String font;
    @XmlAttribute(name = "ratio")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ratio;
    @XmlAttribute(name = "rot")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rot;
    @XmlAttribute(name = "align")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String align;
    @XmlAttribute(name = "distance")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String distance;
    @XmlValue
    protected String value;

    /**
     * Gets the value of the x property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setX(String value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setY(String value) {
        this.y = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the layer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLayer() {
        return layer;
    }

    /**
     * Sets the value of the layer property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLayer(String value) {
        this.layer = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFont() {
        if (font == null) {
            return "proportional";
        }
        else {
            return font;
        }
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFont(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the ratio property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRatio() {
        if (ratio == null) {
            return "8";
        }
        else {
            return ratio;
        }
    }

    /**
     * Sets the value of the ratio property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRatio(String value) {
        this.ratio = value;
    }

    /**
     * Gets the value of the rot property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRot() {
        if (rot == null) {
            return "R0";
        }
        else {
            return rot;
        }
    }

    /**
     * Sets the value of the rot property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRot(String value) {
        this.rot = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAlign() {
        if (align == null) {
            return "bottom-left";
        }
        else {
            return align;
        }
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDistance() {
        if (distance == null) {
            return "50";
        }
        else {
            return distance;
        }
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDistance(String value) {
        this.distance = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getvalue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setvalue(String value) {
        this.value = value;
    }

}
