//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//


package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "via")
public class Via {

    @XmlAttribute(name = "x", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String x;
    @XmlAttribute(name = "y", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String y;
    @XmlAttribute(name = "extent", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extent;
    @XmlAttribute(name = "drill", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String drill;
    @XmlAttribute(name = "diameter")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String diameter;
    @XmlAttribute(name = "shape")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shape;
    @XmlAttribute(name = "alwaysstop")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String alwaysstop;

    /**
     * Gets the value of the x property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setX(String value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setY(String value) {
        this.y = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExtent(String value) {
        this.extent = value;
    }

    /**
     * Gets the value of the drill property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDrill() {
        return drill;
    }

    /**
     * Sets the value of the drill property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDrill(String value) {
        this.drill = value;
    }

    /**
     * Gets the value of the diameter property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDiameter() {
        if (diameter == null) {
            return "0";
        }
        else {
            return diameter;
        }
    }

    /**
     * Sets the value of the diameter property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDiameter(String value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getShape() {
        if (shape == null) {
            return "round";
        }
        else {
            return shape;
        }
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the alwaysstop property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAlwaysstop() {
        if (alwaysstop == null) {
            return "no";
        }
        else {
            return alwaysstop;
        }
    }

    /**
     * Sets the value of the alwaysstop property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAlwaysstop(String value) {
        this.alwaysstop = value;
    }

}
