//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.23 at 08:50:01 AM PDT
//


package org.openpnp.model.eagle.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "wire")
public class Wire {

    @XmlAttribute(name = "x1", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String x1;
    @XmlAttribute(name = "y1", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String y1;
    @XmlAttribute(name = "x2", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String x2;
    @XmlAttribute(name = "y2", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String y2;
    @XmlAttribute(name = "width", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String width;
    @XmlAttribute(name = "layer", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String layer;
    @XmlAttribute(name = "extent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String extent;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String style;
    @XmlAttribute(name = "curve")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String curve;
    @XmlAttribute(name = "cap")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cap;

    /**
     * Gets the value of the x1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getX1() {
        return x1;
    }

    /**
     * Sets the value of the x1 property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setX1(String value) {
        this.x1 = value;
    }

    /**
     * Gets the value of the y1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getY1() {
        return y1;
    }

    /**
     * Sets the value of the y1 property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setY1(String value) {
        this.y1 = value;
    }

    /**
     * Gets the value of the x2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getX2() {
        return x2;
    }

    /**
     * Sets the value of the x2 property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setX2(String value) {
        this.x2 = value;
    }

    /**
     * Gets the value of the y2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getY2() {
        return y2;
    }

    /**
     * Sets the value of the y2 property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setY2(String value) {
        this.y2 = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the layer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLayer() {
        return layer;
    }

    /**
     * Sets the value of the layer property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLayer(String value) {
        this.layer = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExtent(String value) {
        this.extent = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStyle() {
        if (style == null) {
            return "continuous";
        }
        else {
            return style;
        }
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the curve property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurve() {
        if (curve == null) {
            return "0";
        }
        else {
            return curve;
        }
    }

    /**
     * Sets the value of the curve property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCurve(String value) {
        this.curve = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCap() {
        if (cap == null) {
            return "round";
        }
        else {
            return cap;
        }
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCap(String value) {
        this.cap = value;
    }

}
