package org.openpnp.tcpServer;

public enum MessageType {
	HOME, START, STOP, M999, PARK_XY, PARK_Z, MOVE_XP_01_MIL, MOVE_XP_1_MIL, MOVE_XP_10_MIL, MOVE_XM_01_MIL,
	MOVE_XM_1_MIL, MOVE_XM_10_MIL
	, MOVE_YP_01_MIL, MOVE_YP_1_MIL, MOVE_YP_10_MIL, MOVE_YM_01_MIL,
	MOVE_YM_1_MIL, MOVE_YM_10_MIL
	, MOVE_ZP_01_MIL, MOVE_ZP_1_MIL, MOVE_ZP_10_MIL, MOVE_ZM_01_MIL,
	MOVE_ZM_1_MIL, MOVE_ZM_10_MIL}
